name: Docker CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
            uses: actions/checkout@v3

            - name: Set up Docker
            uses: docker/setup-buildx-action@v3

            - name: LS -la
            run: |
                pwd 
                ls -la

    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to server
            uses: appleboy/ssh-action@v1.0.0

            with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USER }}
                key: ${{ secrets.SERVER_SSH_KEY }}
                port: 22
                script: |
                    cd ${{ secrets.DEV_VPS_WORKDIR }}
            
                    git pull origin main
                    docker compose -f docker-compose.yml down
                    docker compose -f docker-compose.yml up -d --build
                    docker ps