name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: LS -la
        run: |
          pwd 
          ls -la

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            if [ ! -d "${{ secrets.DEV_VPS_WORKDIR }}" ]; then
                mkdir -p ${{ secrets.DEV_VPS_WORKDIR }}
                cd $(dirname ${{ secrets.DEV_VPS_WORKDIR }})
                git clone git@github.com:RidloGhifary/ridlos-portofolio.git $(basename ${{ secrets.DEV_VPS_WORKDIR }})
            else
                cd ${{ secrets.DEV_VPS_WORKDIR }}
                git pull origin main
            fi

            docker compose down
            docker compose up -d --build
            docker ps
